- src/communication/xcSession.js
- src/communication/xcWebSocketPublisher.js
- src/communication/xcWebSocketSubscriber.js
- src/configuration/xcConfiguration.js
- src/parser.js
- src/xcomponentAPI.js
- test/Main.js
- test/karma.conf.js
- test/spec/parserSpec.js
- test/spec/xcConfigurationSpec.js
- test/spec/xcConnectionSpec.js
- test/spec/xcWebSocketSubscriberSpec.js
Implementing a xcWebsocketSubcriber.js to listen to incoming messages from a particular state Machine. I also updated the parser and some tests.
> ReactiveXC_3

- src/communication/xcWebSocketPublisher.js
- src/communication/xcWebSocketSubscriber.js
- src/configuration/xcConfiguration.js
- src/parser.js
- test/Main.js
- test/spec/mock/mockPublisherDependencies.js
- test/spec/parserSpec.js
- test/spec/xcConfigurationSpec.js
- test/spec/xcWebSocketPublisherSpec.js
Adding message type parameter in send method
> Reactive xc 7

- README.md
- src/communication/xcWebSocketSubscriber.js
- src/configuration/xcConfiguration.js
- src/xcomponentAPI.js
- test/Main.js
- test/index.html
- test/spec/mock/mockSubscriberDependencies.js
- test/spec/xcWebSocketSubscriberSpec.js
Add xml parameter in constructor of XComponentAPI, fix subscriber (getStateMachineUpdates was not correct because it does not send a subscribe request) and add unscubscribe method.
> Reactive xc 9

- src/communication/xcWebSocketPublisher.js
- src/communication/xcWebSocketSubscriber.js
- src/configuration/xcConfiguration.js
- src/parser.js
- test/spec/mock/mockPublisherDependencies.js
- test/spec/parserSpec.js
- test/spec/xcConfigurationSpec.js
- test/spec/xcWebSocketPublisherSpec.js
Fix send function in items of the received snapshot and add canPublish function
> Reactive xc 21

- README.md
- src/communication/xcWebSocketSubscriber.js
- src/configuration/xcConfiguration.js
- src/parser.js
- test/spec/mock/mockSubscriberDependencies.js
- test/spec/parserSpec.js
- test/spec/xcConfigurationSpec.js
- test/spec/xcWebSocketSubscriberSpec.js
add canSubscribe function with its test
> add canSubscribe function with its test

- README.md
- package.json
- src/communication/xcConnection.js
- src/communication/xcSession.js
- src/communication/xcWebSocketSubscriber.js
- src/configuration/xcWebSocketBridgeConfiguration.js
- src/xcomponentAPI.js
- test/karma.conf.js
- test/spec/xcConnectionSpec.js
Add getXcapi from websocket. To initialize a session, user put the name of the api that he wants to work with
> Reactice xc 37

- package.json
- webpack.config.js
> Webpack: do not bundle modules dependencies

- .gitignore
- README.md
- package.json
- src/communication/xcWebSocketPublisher.ts
- webpack.config.js
> Improve API packaging

- src/communication/xcSession.ts
- src/communication/xcWebSocketSubscriber.ts
- test/spec/xcSessionSpec.ts
- test/spec/xcWebSocketSubscriberSpec.ts
> fix regression in xcWebSocketSubscriber

- src/communication/xcSession.ts
- src/communication/xcWebSocketSubscriber.ts
- src/configuration/xcWebSocketBridgeConfiguration.ts
- test/index.html
- test/index.js
Add heartBeat function. A message is send to the server every 2 minutes until close method on session is called.
> Reactive xc 40

- package.json
- webpack.config.js
> Migration to webpack 2.x + dependencies upgrade

- package.json
- setup-jasmine-env.js
- webpack.config.js
> use jest-jasmine-reporters

- test/spec/xcomponentMessagesSpec.ts
> Issue #41: testing decode server message

- src/communication/xcSession.ts
- src/index.ts
- src/loggerConfiguration.ts
> Reactive xc 61

- src/configuration/apiConfiguration.ts
exceptions are always throw in the same place: in the findXByY methods
> Issue 63: just refactoring code, since the feature was already present

- package.json
- src/communication/xcWebSocketSubscriber.ts
tested with simple example and was able to get messages
> Issue 62: updating to latest version of rx

- README.md
- src/communication/WebSocketPublisher.ts
- src/index.ts
- src/interfaces/Publisher.ts
Update README
Fix types export in index.ts
Add StateMachineRef type in sendWithStateMachineRef signature
> Refactoring

- README.md
- src/communication/WebSocketBridgeCommunication.ts
- src/communication/WebSocketPublisher.ts
- src/communication/WebSocketSession.ts
- src/communication/WebSocketSubscriber.ts
- src/interfaces/Session.ts
- src/interfaces/StateMachineInstance.ts
- src/interfaces/StateMachineRef.ts
- test/spec/WebSocketPublisherSpec.ts
-Update README
-rename canPublish => canSend
-add send method on StateMachineInstance
-refactoring of StateMachineRef creation
> Update README & Refactoring

- .travis.yml
- package.json
- src/communication/WebSocketBridgeCommunication.ts
- src/communication/xcomponentMessages.ts
- tsconfig.json
- yarn.lock
upgrade node
upgrade typescript
fix api list
> fix api list

- package.json
- src/communication/WebSocketSubscriber.ts
> Fixsnapshot
